import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
      <>
      <Head>
              <title>Início - Luena Business Summit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className='text-3xl'>hello</div>
    </>
  )
}

export default Home
